# Generated by Django 5.1.7 on 2025-03-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='name',
            new_name='number',
        ),
    ]
