# Generated by Django 5.1.7 on 2025-03-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_rename_name_classroom_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='number',
            new_name='name',
        ),
    ]
